### ISSUE TITLE
Titobitt

### ISSUE THREAD

**Issue by marlonflore** [GSA/datagov-deploy#1798]
Trackpad[Uploading... Capture+_2020-06-23-18-32-34.png ]

**Comment by adborden** [comment]
Hello!

Thank you for opening a GitHub issue with Data.gov! I'm afraid I don't understand your request so I'm going to close your issue. Please feel free to re-open with any additional information.

**Comment by marlonflore** [comment]
Thank

**Comment by marlonflore** [comment]
Ok
