### ISSUE TITLE
Implement 12 factor app

### ISSUE THREAD

**Issue by dano-reisys** [GSA/datagov-deploy#5]
- [ ] Execute the app as one or more stateless processes #2 
  - [ ] Manage sessions through db (https://github.com/pantheon-systems/wp-native-php-sessions)
  - [ ] Move uploaded files mechanism to S3 (https://wordpress.org/plugins/amazon-s3-and-cloudfront/)
- [ ] Store config in the environment #1 

It would also be a good idea to implement useful features from: 
https://github.com/roots/trellis
https://github.com/roots/bedrock

**Comment by JJediny** [comment]
Moving Discussion over to migration repo

## https://github.com/GSA/catalog-app/issues/3
